apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kcl-function
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: normal
      functionRef:
        name: kcl-function
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          target: Resources
          params:
            name: "input-instance"
          source: |
            {
                apiVersion: "ec2.aws.upbound.io/v1beta1"
                kind: "Instance"
                metadata.name = option("params").name
                spec.forProvider: {
                    ami: "ami-0d9858aa3c6322f73"
                    instanceType: "t2.micro"
                    region: "us-east-2"
                }
            }
