apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kcl-function
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: normal
      functionRef:
        name: kcl-function
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          target: PatchResources
          resources:
            - name: bucket
              base:
                apiVersion: nobu.dev/v1
                kind: Bucket
                metadata:
                  name: bucket
            - name: iam-user
              base:
                apiVersion: nobu.dev/v1
                kind: User
                metadata:
                  name: iam-user
            - name: iam-role
              base:
                apiVersion: nobu.dev/v1
                kind: Role
                metadata:
                  name: iam-role
          source: |
            items = [
                {
                    # Target the bucket by name
                    metadata.name = "bucket"
                    metadata.annotations: {
                        "nobu.dev/cueified": "true",
                        "nobu.dev/app": "someapp",
                    }
                    spec.forProvider.policy: "some-bucket-policy"
                }
                {
                    # Target the user by name
                    metadata.name = "iam-user"
                    metadata.annotations: {
                        "nobu.dev/cueified": "true",
                        "nobu.dev/app": "someapp",
                    }
                    spec.forProvider.name: "somename"
                }
                {
                    # Target the role by name
                    metadata.name = "iam-role"
                    metadata.annotations: {
                        "nobu.dev/cueified": "true",
                        "nobu.dev/app": "someapp",
                    }
                    spec.forProvider.policy: "some-role-policy"
                }
            ]
