apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kcl-function
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: fn-demo.crossplane.io/v1alpha1
    kind: Database
  mode: Pipeline
  pipeline:
    - step: normal
      functionRef:
        name: kcl-function
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          target: Resources
          source: |
            items = [{
                apiVersion: "sql.gcp.upbound.io/v1beta1"
                kind: "DatabaseInstance"
                spec: {
                    forProvider: {
                        project: "test-project"
                        settings: [{databaseFlags: [{
                            name: "log_checkpoints"
                            value: "on"
                        }]}]
                    }
                }
            }]
