apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: nopexample.org/v1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: normal
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        target: Resources
        params:
          name: name
        source: |
          import regex

          name: str = option("params").name or ""
          assert regex.match(name, r"[A-Za-z_][A-Za-z0-9_]*"), "invalid name: ${name}, expected the regex [A-Za-z_][A-Za-z0-9_]*"
          items = [
              {
                  apiVersion = "eks.nobu.dev/v1beta"
                  kind = "XNodepool"
                  metadata.name = name
                  spec.parameters: {
                  	  autoscaling: [{
                  	  	  maxNodeCount: 1
                  	  	  minNodeCount: 1
                  	  }]
                  	  clusterName: "example-injections"
                  	  region: "us-east-2"
                  }
              }
          ]
