apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: my-awesome-dev-bucket
  labels:
    foo: bar
  name: my-awesome-dev-bucket
  namespace: awesome-namespace
spec:
  forProvider:
    region: us-west-1
status:
  atProvider:
    id: random-bucket-id
---
apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: my-awesome-dev-bucket
  labels:
    foo: bar
  name: another-awesome-dev-bucket
  namespace: awesome-namespace
spec:
  forProvider:
    region: us-west-1
status:
  atProvider:
    id: random-bucket-id
