apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: generate desired resources
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: kcl-function-1
      spec:
        source: |
          items = [{
              apiVersion: "v1"
              kind: "XR"
              metadata.annotations: {
                  "krm.kcl.dev/composition-resource-name" = "bucket1"
              }
              spec.forProvider.network: "some-network"
          }, {
              apiVersion: "v1"
              kind: "XR"
              metadata.name = "bucket2"
              spec.forProvider.network: "some-network"
          }]
  - step: patch desired resources
    functionRef:
      name: kcl-function
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: kcl-function-2
      spec:
        target: PatchDesired
        source: |
          items = [{
              metadata.name = "bucket1"
              spec.forProvider.network: "some-override-network1"
          }, {
              metadata.name = "bucket2"
              spec.forProvider.network: "some-override-network2"       
          }]
