run:
	crossplane render xr.yaml composition.yaml functions.yaml -r

oci:
	crossplane render xr.yaml oci_composition.yaml functions.yaml -r

git:
	crossplane render xr.yaml git_composition.yaml functions.yaml -r

local:
	crossplane render xr.yaml local_composition.yaml functions.yaml -r
