name: Function KCL e2e tests
on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  pull_request: {}

env:
  GO_VERSION: '1.24'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Start Function Server
      run: |
        go run . --insecure --debug &
        sleep 10

    - name: Setup the Crossplane CLI
      run: "curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh"

    - name: Run e2e Tests
      run: export PATH=$PATH:$PWD && scripts/e2e.sh
